### PR TITLE
refactor: modules structure

### PR DESCRIPTION
**Pull request by frimoldi**
- Moved logic to `lib.rs`.
- Created `analyzer.rs` module.
- Removed `-l` language param. All analyzers would run, throwing metrics of their own files.

### CODE REVIEW

**Comment by Shogoki** [comment]
very nice. 
Looks good to me.

**Comment by Shogoki** [comment]
Ah, but we should update the Readme, too.
And I think we can bump the version for this.

**Comment by frimoldi** [comment]
Yeah, good call. I'll update the README right away.

**Comment by Shogoki** [comment]
Another thing.
We should add an Analyzer for Go. The current version did support Go, too. 
There was just no transformation done, because Go has a strict formatting guideline builtin.

**Comment by frimoldi** [comment]
- Added `Go` analyzer, with no transformation.
- Updated readme.
- Bumped to v `0.2.0`

cc @Shogoki

**Review by Shogoki — APPROVED** [review]

**Pull request merged**
